name: program_language_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  http: ^1.2.2
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  pinput: ^5.0.0
  provider: ^6.1.2
  mime: ^2.0.0
#  location: ^7.0.1
  flutter_osm_plugin: ^1.3.6
#  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/locales/
    - assets/images/