name: program_language_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3    
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  shimmer: ^3.0.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  http: ^1.2.2
  google_fonts: ^6.2.1
  get_it: ^8.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/locales/
#  fonts:
#    - family: Schyler
#      fonts:
#        - asset: fonts/Schyler-Regular.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
#    - family: Trajan Pro
#      fonts:
#        - asset: fonts/TrajanPro.ttf
#        - asset: fonts/TrajanPro_Bold.ttf
#          weight: 700
